"""add routing key to notification table

Revision ID: b267f5370b44
Revises: 8896d5105979
Create Date: 2025-08-15 16:52:14.009994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b267f5370b44'
down_revision: Union[str, Sequence[str], None] = '8896d5105979'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verification_code', sa.Column('routing_key', sa.Enum('ACCOUNT_VERIFICATION', 'PASSWORD_RESET', name='verificationcoderoutingkey'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verification_code', 'routing_key')
    # ### end Alembic commands ###
