"""add is_created_manually to user

Revision ID: eb0377a77536
Revises: 93131fc9aeba
Create Date: 2026-06-29 23:29:11.683766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb0377a77536'
down_revision: Union[str, Sequence[str], None] = '93131fc9aeba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user',
        sa.Column('is_created_manually', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    op.drop_column('user', 'is_created_manually')
    # ### end Alembic commands ###
